declare module "./assets/css/presets/Wind" {
	const Wind: {
		global: any
		directives: {
			tooltip: any
			badgedirective: any
			ripple: any
		}
		autocomplete: any
		calendar: any
		cascadeselect: any
		checkbox: any
		chips: any
		colorpicker: any
		dropdown: any
		floatlabel: any
		iconfield: any
		inputgroup: any
		inputotp: any
		inputgroupaddon: any
		inputmask: any
		inputnumber: any
		inputswitch: any
		inputtext: any
		knob: any
		listbox: any
		multiselect: any
		password: any
		radiobutton: any
		rating: any
		selectbutton: any
		slider: any
		textarea: any
		togglebutton: any
		treeselect: any
		tristatecheckbox: any
		button: any
		speeddial: any
		splitbutton: any
		datatable: any
		dataview: any
		orderlist: any
		organizationchart: any
		paginator: any
		picklist: any
		tree: any
		treetable: any
		timeline: any
		accordion: any
		card: any
		deferred: any
		divider: any
		fieldset: any
		panel: any
		scrollpanel: any
		splitter: any
		stepper: any
		tabview: any
		toolbar: any
		confirmpopup: any
		dialog: any
		overlaypanel: any
		sidebar: any
		fileupload: any
		breadcrumb: any
		contextmenu: any
		dock: any
		menu: any
		menubar: any
		megamenu: any
		panelmenu: any
		steps: any
		tabmenu: any
		tieredmenu: any
		message: any
		inlinemessage: any
		toast: any
		carousel: any
		galleria: any
		image: any
		avatar: any
		badge: any
		blockui: any
		chip: any
		inplace: any
		metergroup: any
		scrolltop: any
		skeleton: any
		progressbar: any
		progressspinner: any
		tag: any
		terminal: any
	}
	export default Wind
}
